name: dockhand

services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    volumes:
      - ./data:/app/data
      - ./compose.yaml:/app/compose.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 100.94.16.8:3000:3000
    restart: unless-stopped

networks:
  default:
    name: dockhand_network
    external: true
