name: dockhand

services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    volumes:
      - ${HOME_DIR}:${HOME_DIR}
      - ${DOCKHAND_DATA}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT:-3000}:3000
    restart: unless-stopped

networks:
  default:
    name: dockhand_network
    external: true
