services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME_DIR}/.dockhand/data:/app/data
      - ${HOME_DIR}/:${HOME_DIR}
    ports:
      - ${PORT:-3000}:3000
    restart: unless-stopped

networks:
  default:
    name: dockhand_network
